import { LoanTypeAccent, LoanTypeOption } from "./types";

const PURPLE: LoanTypeAccent = { bg: "#EEEDFE", text: "#26215C", border: "#AFA9EC" };
const TEAL: LoanTypeAccent = { bg: "#E1F5EE", text: "#04342C", border: "#5DCAA5" };
const AMBER: LoanTypeAccent = { bg: "#FDF2D8", text: "#6B4E00", border: "#E8C165" };
const MAROON: LoanTypeAccent = { bg: "#FBEAF0", text: "#4B1528", border: "#ED93B1" };
const BROWN: LoanTypeAccent = { bg: "#FAECE7", text: "#4A1B0C", border: "#F0997B" };
const BLUE: LoanTypeAccent = { bg: "#E3EEFB", text: "#14315C", border: "#8FB4E8" };
const GREEN: LoanTypeAccent = { bg: "#E7F6E9", text: "#1C4A24", border: "#7FCB8E" };

export const LOAN_TYPES: LoanTypeOption[] = [
  {
    id: "C01",
    code: "C01",
    name: "Personal Loan",
    icon: "person-outline",
    amountRange: "₹25,000 - ₹10,00,000",
    rateTenure: "From 14% · Up to 60 months",
    badgeIcon: "flash-outline",
    badgeText: "Disbursed in 24 hours",
    accent: PURPLE,
    isMicrofinance: false,
  },
  {
    id: "C02",
    code: "C02",
    name: "Business / MSME Loan",
    icon: "briefcase-outline",
    amountRange: "₹50,000 - ₹50,00,000",
    rateTenure: "From 16% · Up to 84 months",
    badgeIcon: "flash-outline",
    badgeText: "Disbursed in 48 hours",
    accent: TEAL,
    isMicrofinance: false,
  },
  {
    id: "C03",
    code: "C03",
    name: "Gold Loan",
    icon: "diamond-outline",
    amountRange: "₹5,000 - ₹25,00,000",
    rateTenure: "From 9% · Up to 12 months",
    badgeIcon: "location-outline",
    badgeText: "Branch only",
    accent: AMBER,
    isMicrofinance: false,
  },
  {
    id: "C04",
    code: "C04",
    name: "Two-Wheeler Loan",
    icon: "bicycle-outline",
    amountRange: "₹20,000 - ₹2,00,000",
    rateTenure: "From 12% · Up to 36 months",
    badgeIcon: "flash-outline",
    badgeText: "Disbursed in 24 hours",
    accent: BROWN,
    isMicrofinance: false,
  },
  {
    id: "C05",
    code: "C05",
    name: "Group Loan (JLG)",
    icon: "people-outline",
    amountRange: "₹10,000 - ₹1,00,000 (per member)",
    rateTenure: "From 20% · Up to 24 months",
    badgeIcon: "people-outline",
    badgeText: "Centre meeting required",
    accent: MAROON,
    isMicrofinance: true,
  },
  {
    id: "C06",
    code: "C06",
    name: "Home Loan",
    icon: "home-outline",
    amountRange: "₹5,00,000 - ₹75,00,000",
    rateTenure: "From 8.5% · Up to 240 months",
    badgeIcon: "document-text-outline",
    badgeText: "Property documents required",
    accent: BLUE,
    isMicrofinance: false,
  },
  {
    id: "C07",
    code: "C07",
    name: "Education Loan",
    icon: "school-outline",
    amountRange: "₹50,000 - ₹20,00,000",
    rateTenure: "From 10% · Up to 96 months",
    badgeIcon: "school-outline",
    badgeText: "Admission proof required",
    accent: GREEN,
    isMicrofinance: false,
  },
  {
    id: "C08",
    code: "C08",
    name: "Loan Against Property",
    icon: "business-outline",
    amountRange: "₹2,00,000 - ₹1,00,00,000",
    rateTenure: "From 11% · Up to 180 months",
    badgeIcon: "document-text-outline",
    badgeText: "Property documents required",
    accent: PURPLE,
    isMicrofinance: false,
  },
  {
    id: "C09",
    code: "C09",
    name: "Agriculture Loan",
    icon: "leaf-outline",
    amountRange: "₹10,000 - ₹5,00,000",
    rateTenure: "From 7% · Up to 60 months",
    badgeIcon: "leaf-outline",
    badgeText: "Kisan Credit Card linked",
    accent: TEAL,
    isMicrofinance: false,
  },
  {
    id: "C10",
    code: "C10",
    name: "Vehicle Loan (Four-Wheeler)",
    icon: "car-sport-outline",
    amountRange: "₹1,00,000 - ₹15,00,000",
    rateTenure: "From 10% · Up to 84 months",
    badgeIcon: "flash-outline",
    badgeText: "Disbursed in 48 hours",
    accent: AMBER,
    isMicrofinance: false,
  },
];
