export const NAVIGATE_NAME = {
    LOGIN: 'Login',
    REGISTER: 'Register',
    AIWEALTH_COACH_SCREEN: 'AIWealthCoachScreen',
    CUSTOMER_ONBOARDING_SCREEN: 'CustomerOnboardingScreen',
    COB_LIST_SCREEN:'COBListScreen',
    LOAN_TYPE_SELECTION_SCREEN: 'LoanTypeSelectionScreen',
    LOAN_APPROVAL_SCREEN: 'LoanApprovalScreen',
    PRE_DISBURSEMENT_SCREEN: 'PreDisbursementScreen',
    REPAYMENT_SCREEN: 'RepaymentScreen',
    LOAN_ORIGINATION_SCREEN: 'LoanOriginationScreen',
    APPROVAL_QUEUE_SCREEN: 'ApprovalQueueScreen',
    EDIT_PROFILE_SCREEN: 'EditProfileScreen',
    DOCUMENTS_KYC_SCREEN: 'DocumentsKYCScreen',
    CHANGE_PASSWORD_SCREEN: 'ChangePasswordScreen',
    MY_PERFORMANCE_SCREEN: 'MyPerformanceScreen',
    MY_CENTRES_SCREEN: 'MyCentresScreen',
    MEETING_SCREEN: 'MeetingScreen',
}