import { Centre } from "./types";

export const centres: Centre[] = [
  {
    id: "c1",
    code: "CTR_1001",
    name: "Rampur Mahila Kendra",
    village: "Rampur",
    meetingDay: "Monday",
    memberCount: 24,
    targetMemberCount: 30,
    status: "ACTIVE",
    repaymentHealthScore: 88,
  },
  {
    id: "c2",
    code: "CTR_1002",
    name: "Bhatauli Vikas Kendra",
    village: "Bhatauli",
    meetingDay: "Wednesday",
    memberCount: 18,
    targetMemberCount: 25,
    status: "ACTIVE",
    repaymentHealthScore: 74,
  },
  {
    id: "c3",
    code: "CTR_1003",
    name: "Kalyanpur Pragati Kendra",
    village: "Kalyanpur",
    meetingDay: "Friday",
    memberCount: 12,
    targetMemberCount: 25,
    status: "FORMING",
    repaymentHealthScore: 60,
  },
  {
    id: "c4",
    code: "CTR_1004",
    name: "Shahpur Unnati Kendra",
    village: "Shahpur",
    meetingDay: "Tuesday",
    memberCount: 27,
    targetMemberCount: 30,
    status: "ACTIVE",
    repaymentHealthScore: 92,
  },
  {
    id: "c5",
    code: "CTR_1005",
    name: "Maldah Sakhi Kendra",
    village: "Maldah",
    meetingDay: "Saturday",
    memberCount: 9,
    targetMemberCount: 20,
    status: "FORMING",
    repaymentHealthScore: 55,
  },
];
